In [1]:
import numpy as np
a = [i for i in range(9)]

In [2]:
[(a,b) for a,b in zip([1,2,3], [4,5,6])]

[(1, 4), (2, 5), (3, 6)]

In [3]:
from ultimate_tictactoe import UltimateTicTacToe

ttt = UltimateTicTacToe()
print(str(ttt))

_ _ _  _ _ _  _ _ _
_ _ _  _ _ _  _ _ _
_ _ _  _ _ _  _ _ _

_ _ _  _ _ _  _ _ _
_ _ _  _ _ _  _ _ _
_ _ _  _ _ _  _ _ _

_ _ _  _ _ _  _ _ _
_ _ _  _ _ _  _ _ _
_ _ _  _ _ _  _ _ _


In [4]:
a = ["1","2","3"]
print("".join(a[0:3]))

123


In [5]:
from utt2 import UTTNode
node = UTTNode()
print(str(node))

_ _ _  _ _ _  _ _ _
_ _ _  _ _ _  _ _ _
_ _ _  _ _ _  _ _ _

_ _ _  _ _ _  _ _ _
_ _ _  _ _ _  _ _ _
_ _ _  _ _ _  _ _ _

_ _ _  _ _ _  _ _ _
_ _ _  _ _ _  _ _ _
_ _ _  _ _ _  _ _ _




In [6]:
node.top_board

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
print(node.prev_move)

None


In [8]:
moves = node.legal_moves()
print(moves)

[(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (0, 8), (1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (2, 0), (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (2, 7), (2, 8), (3, 0), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7), (3, 8), (4, 0), (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 7), (4, 8), (5, 0), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (5, 7), (5, 8), (6, 0), (6, 1), (6, 2), (6, 3), (6, 4), (6, 5), (6, 6), (6, 7), (6, 8), (7, 0), (7, 1), (7, 2), (7, 3), (7, 4), (7, 5), (7, 6), (7, 7), (7, 8), (8, 0), (8, 1), (8, 2), (8, 3), (8, 4), (8, 5), (8, 6), (8, 7), (8, 8)]


In [9]:
tuple(np.random.default_rng().choice(moves, 1, replace=False, axis = 0)[0])

(0, 5)

In [10]:
node.top_board

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:

print("MOVES: ", moves)
end = node.play(tuple(np.random.default_rng().choice(moves, 1, replace=False, axis = 0)[0]))
while end is None:
    moves = node.legal_moves()
    end = node.play(tuple(np.random.default_rng().choice(moves, 1, replace=False, axis = 0)[0]))
print(node)

MOVES:  [(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (0, 8), (1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (2, 0), (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (2, 7), (2, 8), (3, 0), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7), (3, 8), (4, 0), (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 7), (4, 8), (5, 0), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (5, 7), (5, 8), (6, 0), (6, 1), (6, 2), (6, 3), (6, 4), (6, 5), (6, 6), (6, 7), (6, 8), (7, 0), (7, 1), (7, 2), (7, 3), (7, 4), (7, 5), (7, 6), (7, 7), (7, 8), (8, 0), (8, 1), (8, 2), (8, 3), (8, 4), (8, 5), (8, 6), (8, 7), (8, 8)]
x o x  x x x  o o _
o x _  _ o _  o _ _
_ x x  o o x  o _ _

_ x _  o o _  o _ _
_ x _  _ o x  _ _ _
_ x _  o _ x  o _ _

x x _  o x _  o o x
x x _  o _ x  _ _ _
_ _ x  _ _ o  o x o




In [12]:
print(node)

x o x  x x x  o o _
o x _  _ o _  o _ _
_ x x  o o x  o _ _

_ x _  o o _  o _ _
_ x _  _ o x  _ _ _
_ x _  o _ x  o _ _

x x _  o x _  o o x
x x _  o _ x  _ _ _
_ _ x  _ _ o  o x o




In [13]:
print(end)

-1


In [14]:
node.bot_boards[1]

array([ 1,  1,  1,  0, -1,  0, -1, -1,  1])

In [15]:
board = np.array(node.bot_boards[1]).reshape(3,3)

In [16]:
WIN_X = np.array([1,1,1])
WIN_O = np.array([-1,-1,-1])

In [17]:
print(np.all(board == WIN_X,axis=0).any(), # 3 in a row horizontally/vertically
             np.all(board == WIN_X,axis=1).any(),
             np.all(board.diagonal() == WIN_X), # 3 in a row on the diagonal
             np.all(np.flipud(board).diagonal()==WIN_X))

False True False False
